config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users, :controllers => { registrations: 'registrations' }


  resources :boards
  resources :notices

  resources :users do
    post 'add_postcode', on: :collection
  end

  resources :issues do
      resources :comments
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
  validates :title, :content, :presence => true

  mount_uploader :image, NoticeImageUploader
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.where(["location = ?", "current_user.location"])
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    @notice = Notice.find(params[:id])
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)
    @notice.user_id = current_user.id
    @notice.postcode = current_user.postcode
    @notice.location = current_user.location
    @notice.classification = "notice"

    respond_to do |format|
      if @notice.save
        format.html { redirect_to root_path, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to root_path, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:user_id, :title, :content, :image)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= form_for(notice, html: {:multipart=>true }) do |f| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>
<%= link_to 'Back', root_path %>
<%= render 'form', notice: @notice %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notices</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.user %></td>
        <td><%= notice.title %></td>
        <td><%= notice.content %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<div class="container vertical-center">
<h1><%=current_user.location %></h1>
<h2>Community Board</h2>
<h3>New Notice</h3>
<%= link_to root_path, class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
<% end %><br><br>
<%= link_to "Issue", new_issue_path %>

<%= render 'form', notice: @notice %>
</div>

app/views/notices/show.html.erb
<div class="container vertical-center">
<p id="notice"><%= notice %></p>
<%= link_to root_path, class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
<% end %>

<h1><%= @notice.classification.capitalize %></h1>

<p>
  <strong><%= @notice.title.capitalize %></strong>
</p>

<p>
  By:
  <%= @notice.user.firstname.capitalize %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notice.content.capitalize %>
</p>



<% if @notice.image.file.nil? %>
<% else %>
<%= image_tag(@notice.image_url(:standard)) %>
<% end %>




<% if @notice.user_id == current_user.id %>
<%= link_to 'Edit', edit_notice_path(@notice) %>
<% else %>
<% end%>

</div>