config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users, :controllers => { registrations: 'registrations' }


  resources :boards
  resources :notices

  resources :users do
    post 'add_postcode', on: :collection
  end

  resources :issues do
      resources :comments
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, :content, :presence => true
  mount_uploader :image, IssueUploader
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.where(["location = ?", "current_user.location"])
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(["issue_id=?",@issue.id])
    @comments = @comments.sort_by {|c| Time.now - c.updated_at}
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.user_id = current_user.id
    @issue.postcode = current_user.postcode
    @issue.receipt = generate_random
    @issue.location = current_user.location
    @issue.classification = "issue"

    respond_to do |format|
      if @issue.save
        format.html { redirect_to root_path, notice: "Issue was successfully created." }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:user_id, :title, :content, :receipt, :image)
    end

    def generate_random
      @receipt = []
      4.times do |x|
        x = 1 + rand(9)
        @receipt << x.to_s
      end
      if Issue.where("receipt = ?", @receipt.join).first
        generate_random
      else
        return @receipt.join
      end
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for(issue) do |f| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>
<%= link_to 'Back', root_path %>
<%= render 'form', issue: @issue %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th>Receipt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.user %></td>
        <td><%= issue.title %></td>
        <td><%= issue.content %></td>
        <td><%= issue.receipt %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<div class="container vertical-center">
<h1><%=current_user.location %></h1>
<h2>Community Board</h2>
<h3>New Issue</h3>
<%= link_to root_path, class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-chevron-left"></span>
<% end %><br><br>
<%= link_to "Notice", new_notice_path %>

<%= render 'form', issue: @issue %>
</div>

app/views/issues/show.html.erb
<div class="container vertival-center">
  <%= link_to root_path, class: "btn btn-default" do %>
      <span class="glyphicon glyphicon-chevron-left"></span>
  <% end %>


<h1><%= @issue.classification.capitalize%></h1>
<h3>
  <%= @issue.title.capitalize %>
</h3>

<p>
  Reference No.
  <strong><%= @issue.receipt %></strong>
</p>

<p>
  By:
  <%= @issue.user.firstname.capitalize %>
</p>

<p>
  <%= @issue.content.capitalize %>
</p>



<% if @issue.image.file.nil? %>
<% else %>
<%= image_tag(@issue.image_url(:standard)) %>
<% end %>

<% if @issue.user_id == current_user.id %>
<%= link_to "Delete Issue", issue_path(:id => @issue.id), method: :delete, data: { confirm: 'All associated comments will also be deleted, are you sure?' } %>
<% else %>
<% end%>
<%= render "comments/form", comment: @comment %>

<table class="table table-striped">
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user.firstname %></td>
        <% if comment.user_id == current_user.id %>
        <td><%= link_to 'Delete comment', issue_comment_path(:issue_id=>comment.issue_id, :id=>comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

</div>