config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users, :controllers => { registrations: 'registrations' }


  resources :boards
  resources :notices

  resources :users do
    post 'add_postcode', on: :collection
  end

  resources :issues do
      resources :comments
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="container vertical-center">
<h1><%=current_user.location %></h1>
<h2>Community Board</h2>


<%= link_to new_notice_path, class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-edit"></span>
<% end %><br><br>

      <% @posts.each do |post| %>
        <div class="panel panel-default">
          <div class="panel-body">
          <h3><%= post.title.capitalize %></h3>
          <p><%= post.user.firstname %></p>
          <% if post.classification == "issue"%>
            <td><%= link_to issue_path(:id => post.id), class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-eye-open"></span>
            <% end %></td>
          <% else %>
          <td><%= link_to notice_path(:id => post.id), class: "btn btn-default" do %>
              <span class="glyphicon glyphicon-eye-open"></span>
          <% end %></td>
          <% end %>
        </div>
        </div>
      <% end %>
</div>

app/views/pages/landing.html.erb
<body class="homepage">
  <div class="container vertical-center">
    <h1>
    Welcome to your local community board.
  </h1>
  </div>
</body>